name: Deploy
on:
  push:
    tags:
    - "*"

jobs:

  build_and_publish:
    runs-on: ubuntu-latest
    # needs: [test]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Publish
      run: |
        npm ci
        npm publish
      env:
        NODE_ENV: "development"
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
